# Generated by Django 4.2.11 on 2024-04-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productreview_productquestion_productanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productanswer',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productquestion',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
